-- ============================================================================
-- ITEMS - Add these to your RSG Core shared items
-- You will need to add these items to your rsg-core/shared/items.lua
-- ITEMS THAT ARE COMMENTED OUT, SIMPLY DO NOT HAVE IMAGES PROVIDED BY DIAMONDBACK SCRIPTS
-- ALL ITEMS WILL EVENTUALLY COME WITH IMAGES. PLEASE BE PATIENT AND LOOK FOR UPDATES!
-- ============================================================================
 ['collectors_bag']           = { name = 'collectors_bag',           label = "Collector's Bag",           weight = 500,  type = 'item', image = 'collectors_bag.png',           unique = true,  useable = true,  shouldClose = true,  description = 'Essential storage for collectibles.' },
 ['metal_detector']           = { name = 'metal_detector',           label = 'Metal Detector',            weight = 1000, type = 'item', image = 'metal_detector.png',           unique = true,  useable = true,  shouldClose = true,  description = 'Detects buried metal objects.' },
 ['refined_binoculars']       = { name = 'refined_binoculars',       label = 'Refined Binoculars',        weight = 500,  type = 'item', image = 'refined_binoculars.png',       unique = true,  useable = true,  shouldClose = true,  description = 'High-quality binoculars for spotting collectibles.' },
 ['shovel']                   = { name = 'shovel',                   label = 'Pennington Field Shovel',   weight = 1500, type = 'item', image = 'shovel.png',                   unique = true,  useable = true,  shouldClose = true,  description = 'A sturdy shovel for digging.' },
 ['collectors_lantern']       = { name = 'collectors_lantern',       label = "Collector's Lantern",       weight = 300,  type = 'item', image = 'collectors_lantern.png',       unique = true,  useable = true,  shouldClose = true,  description = 'Reveals hidden markings.' },
 ['map_coins']                = { name = 'map_coins',                label = 'Coin Collection Map',       weight = 50,   type = 'item', image = 'map_coins.png',                unique = false, useable = true,  shouldClose = true,  description = 'Reveals rare coin locations.' },
 ['map_arrowheads']           = { name = 'map_arrowheads',           label = 'Arrowhead Collection Map',  weight = 50,   type = 'item', image = 'map_arrowheads.png',           unique = false, useable = true,  shouldClose = true,  description = 'Points to ancient arrowheads.' },
 ['map_jewelry']              = { name = 'map_jewelry',              label = 'Lost Jewelry Map',          weight = 50,   type = 'item', image = 'map_jewelry.png',              unique = false, useable = true,  shouldClose = true,  description = 'Leads to valuable lost jewelry.' },
 ['map_bottles']              = { name = 'map_bottles',              label = 'Antique Bottles Map',       weight = 50,   type = 'item', image = 'map_bottles.png',              unique = false, useable = true,  shouldClose = true,  description = 'Reveals rare antique bottles.' },
 ['map_fossils']              = { name = 'map_fossils',              label = 'Fossil Collection Map',     weight = 50,   type = 'item', image = 'map_fossils.png',              unique = false, useable = true,  shouldClose = true,  description = 'Points to rare fossils.' },
 ['map_heirlooms']            = { name = 'map_heirlooms',            label = 'Family Heirlooms Map',      weight = 50,   type = 'item', image = 'map_heirlooms.png',            unique = false, useable = true,  shouldClose = true,  description = 'Reveals valuable family heirlooms.' },
 ['health_tonic']             = { name = 'health_tonic',             label = 'Health Tonic',              weight = 200,  type = 'item', image = 'health_tonic.png',             unique = false, useable = true,  shouldClose = true,  description = 'Restores health.' },
 ['stamina_tonic']            = { name = 'stamina_tonic',            label = 'Stamina Tonic',             weight = 200,  type = 'item', image = 'stamina_tonic.png',            unique = false, useable = true,  shouldClose = true,  description = 'Restores stamina.' },
-- ['deadeye_tonic']            = { name = 'deadeye_tonic',            label = 'Dead Eye Tonic',            weight = 200,  type = 'item', image = 'deadeye_tonic.png',            unique = false, useable = true,  shouldClose = true,  description = 'Restores Dead Eye.' },
-- ['horse_medicine']           = { name = 'horse_medicine',           label = 'Horse Medicine',            weight = 300,  type = 'item', image = 'horse_medicine.png',           unique = false, useable = true,  shouldClose = true,  description = 'Heals your horse.' },
 ['tarot_card_pack']          = { name = 'tarot_card_pack',          label = 'Tarot Card Pack',           weight = 100,  type = 'item', image = 'tarot_card_pack.png',          unique = false, useable = true,  shouldClose = true,  description = 'Mysterious tarot cards.' },
 ['crystal_ball_trinket']     = { name = 'crystal_ball_trinket',     label = 'Crystal Ball Trinket',      weight = 200,  type = 'item', image = 'crystal_ball_trinket.png',     unique = true,  useable = true,  shouldClose = true,  description = 'Said to bring luck.' },
-- ['romani_charm']             = { name = 'romani_charm',             label = 'Romani Protection Charm',   weight = 50,   type = 'item', image = 'romani_charm.png',             unique = true,  useable = true,  shouldClose = true,  description = 'Wards off evil spirits.' },
-- ['collectible_coin']          = { name = 'collectible_coin',          label = 'Collectible Coin',           weight = 100,  type = 'item', image = 'collectible_coin.png',          unique = false, useable = true,  shouldClose = true,  description = 'A rare collectible coin.' },
-- ['collectible_antique']     = { name = 'collectible_antique',     label = 'Collectible Antique',      weight = 200,  type = 'item', image = 'collectible_antique.png',     unique = true,  useable = true,  shouldClose = true,  description = 'A rare collectible antique.' },
-- ['collectible_gemstone']      = { name = 'collectible_gemstone',             label = 'Collectible Gemstone',   weight = 50,   type = 'item', image = 'collectible_gemstone.png',             unique = true,  useable = true,  shouldClose = true,  description = 'A rare collectible gemstone.' },

----------------------------------
----------- Rare Sets ------------
----------------------------------
-- Coins
 ['collectible_coin_1792_quarter']         = { name = 'collectible_coin_1792_quarter',         label = '1792 Quarter',        weight = 10,   type = 'item', image = 'collectible_coin_1792_quarter.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable 1792 quarter.' },
 ['collectible_coin_1797_half_eagle']         = { name = 'collectible_coin_1797_half_eagle',         label = '1797 Half Eagle',        weight = 10,   type = 'item', image = 'collectible_coin_1797_half_eagle.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable 1797 Half Eagle.' },
 ['collectible_coin_1800_gold_dollar']         = { name = 'collectible_coin_1800_gold_dollar',         label = '1800 Gold Dollar',        weight = 10,   type = 'item', image = 'collectible_coin_1800_gold_dollar.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable 1800 Gold Dollar.' },
 ['collectible_coin_morgan_dollar']         = { name = 'collectible_coin_morgan_dollar',         label = 'Morgan Dollar',        weight = 10,   type = 'item', image = 'collectible_coin_morgan_dollar.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable Morgan Dollar.' },
 ['collectible_coin_liberty_seated']         = { name = 'collectible_coin_liberty_seated',         label = 'Liberty Seated Coin',        weight = 10,   type = 'item', image = 'collectible_coin_liberty_seated.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable Liberty Seated Coin.' },

-- Arrowheads
 ['collectible_arrow_agate']         = { name = 'collectible_arrow_agate',         label = 'Agate Arrowhead',        weight = 10,   type = 'item', image = 'collectible_arrow_agate.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable agate arrowhead.' },
 ['collectible_arrow_bone']         = { name = 'collectible_arrow_bone',         label = 'Bone Arrowhead',        weight = 10,   type = 'item', image = 'collectible_arrow_bone.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable bone arrowhead.' },
 ['collectible_arrow_obsidian']         = { name = 'collectible_arrow_obsidian',         label = 'Obsidian Arrowhead',        weight = 10,   type = 'item', image = 'collectible_arrow_obsidian.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable obsidian arrowhead.' },
 ['collectible_arrow_quartz']         = { name = 'collectible_arrow_quartz',         label = 'Quartz Arrowhead',        weight = 10,   type = 'item', image = 'collectible_arrow_quartz.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable quartz arrowhead.' },
 ['collectible_arrow_raw_flint']         = { name = 'collectible_arrow_raw_flint',         label = 'Raw Flint Arrowhead',        weight = 10,   type = 'item', image = 'collectible_arrow_raw_flint.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable raw flint arrowhead.' },

-- Jewelry
 ['collectible_jewel_emerald_ring']         = { name = 'collectible_jewel_emerald_ring',         label = 'Emerald Ring',        weight = 10,   type = 'item', image = 'collectible_jewel_emerald_ring.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable emerald ring.' },
 ['collectible_jewel_gold_necklace']         = { name = 'collectible_jewel_gold_necklace',         label = 'Gold Necklace',        weight = 10,   type = 'item', image = 'collectible_jewel_gold_necklace.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable gold necklace.' },
 ['collectible_jewel_ruby_bracelet']         = { name = 'collectible_jewel_ruby_bracelet',         label = 'Ruby Bracelet',        weight = 10,   type = 'item', image = 'collectible_jewel_ruby_bracelet.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable ruby bracelet.' },
 ['collectible_jewel_sapphire_earring']         = { name = 'collectible_jewel_sapphire_earring',         label = 'Sapphire Earring',        weight = 10,   type = 'item', image = 'collectible_jewel_sapphire_earring.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable sapphire earring.' },
 ['collectible_jewel_diamond_brooch']         = { name = 'collectible_jewel_diamond_brooch',         label = 'Diamond Brooch',        weight = 10,   type = 'item', image = 'collectible_jewel_diamond_brooch.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable diamond brooch.' },

-- Bottles
 ['collectible_bottle_cognac']         = { name = 'collectible_bottle_cognac',         label = 'Cognac Bottle',        weight = 10,   type = 'item', image = 'collectible_bottle_cognac.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable cognac bottle.' },
 ['collectible_bottle_bourbon']         = { name = 'collectible_bottle_bourbon',         label = 'Bourbon Bottle',        weight = 10,   type = 'item', image = 'collectible_bottle_bourbon.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable bourbon bottle.' },
 ['collectible_bottle_gin']         = { name = 'collectible_bottle_gin',         label = 'Gin Bottle',        weight = 10,   type = 'item', image = 'collectible_bottle_gin.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable gin bottle.' },
 ['collectible_bottle_rum']         = { name = 'collectible_bottle_rum',         label = 'Rum Bottle',        weight = 10,   type = 'item', image = 'collectible_bottle_rum.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable rum bottle.' },
 ['collectible_bottle_absinthe']         = { name = 'collectible_bottle_absinthe',         label = 'Absinthe Bottle',        weight = 10,   type = 'item', image = 'collectible_bottle_absinthe.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable absinthe bottle.' },

-- Fossils
 ['collectible_fossil_tooth']         = { name = 'collectible_fossil_tooth',         label = 'Fossil Tooth',        weight = 10,   type = 'item', image = 'collectible_fossil_tooth.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable fossil tooth.' },
 ['collectible_fossil_claw']         = { name = 'collectible_fossil_claw',         label = 'Fossil Claw',        weight = 10,   type = 'item', image = 'collectible_fossil_claw.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable fossil claw.' },
-- ['collectible_fossil_shell']         = { name = 'collectible_fossil_shell',         label = 'Fossil Shell',        weight = 10,   type = 'item', image = 'collectible_fossil_shell.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable fossil shell.' },
-- ['collectible_fossil_bone']         = { name = 'collectible_fossil_bone',         label = 'Fossil Bone',        weight = 10,   type = 'item', image = 'collectible_fossil_bone.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable fossil bone.' },
-- ['collectible_fossil_amber']         = { name = 'collectible_fossil_amber',         label = 'Fossil Amber',        weight = 10,   type = 'item', image = 'collectible_fossil_amber.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable fossil amber.' },

-- Heirlooms
-- ['collectible_heir_pocketwatch']         = { name = 'collectible_heir_pocketwatch',         label = 'Heirloom Pocket Watch',        weight = 10,   type = 'item', image = 'collectible_heir_pocketwatch.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable heirloom pocket watch.' },
-- ['collectible_heir_locket']         = { name = 'collectible_heir_locket',         label = 'Heirloom Locket',        weight = 10,   type = 'item', image = 'collectible_heir_locket.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable heirloom locket.' },
-- ['collectible_heir_compass']         = { name = 'collectible_heir_compass',         label = 'Heirloom Compass',        weight = 10,   type = 'item', image = 'collectible_heir_compass.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable heirloom compass.' },
-- ['collectible_heir_music_box']         = { name = 'collectible_heir_music_box',         label = 'Heirloom Music Box',        weight = 10,   type = 'item', image = 'collectible_heir_music_box.png',         unique = false, useable = false, shouldClose = false, description = 'A collectable heirloom music box.' },
-- ['collectible_heir_war_medal']         = { name = 'collectible_heir_war_medal',         label = 'Heirloom War Medal',        weight = 10,   type = 'item', image = 'collectible_heir_war_medal.png',         unique = false, useable =
